# Generated by Django 4.1.3 on 2022-12-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_client_options_client_right_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='current_answer',
            field=models.BooleanField(default=False),
        ),
    ]
