# Generated by Django 4.1.3 on 2022-12-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_client_current_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='right_answers',
            field=models.IntegerField(blank=True, null=True, verbose_name='правильные_ответы'),
        ),
    ]
