# Generated by Django 4.1.3 on 2022-12-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='answered_or_not',
            field=models.BooleanField(default=False),
        ),
    ]
