# Generated by Django 4.1.3 on 2022-12-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_questions_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='number_of_question',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='number_of_correct_answer',
            field=models.IntegerField(blank=True, null=True, verbose_name='номер_правильного_ответа'),
        ),
    ]
