# Generated by Django 4.1.3 on 2022-12-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_questions_number_of_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='number_of_question',
            field=models.IntegerField(blank=True, null=True, verbose_name='какой по счёту данный вопрос'),
        ),
    ]
